### PR TITLE
feat: hyde config

### LINKED ISSUE #16: Interface: option to change swww transition
from https://github.com/prasanthrangan/hyprdots/issues/2040 

Add a new variable in hyderc.

### PR DESCRIPTION
**Pull request by kRHYME7**
# Pull Request

closes #16  #17 

# Main configuration of HyDE. 
https://github.com/HyDE-Project/HyDE/pull/27/files#diff-31daa410486128f22eb0f13834e4b2744c50d57157bc0b8b1702ab5733858dc0

hyde.conf/hyderc is not future proof and it is very fragile.

Please ask questions if you're interested.

### CODE REVIEW

**Comment by kRHYME7** [comment]
@rubiin @abenezerw @T-Crypt

**Comment by rubiin** [comment]
wont be able to test this but looks good so far.

**Comment by kRHYME7** [comment]
@rubiin  I'm bad at naming, should we name it `~/.config/hyde/hyde.toml` or `~/.config/hyde/config.toml `  ??

**Comment by rubiin** [comment]
> @rubiin I'm bad at naming, should we name it `~/.config/hyde/hyde.toml` or `~/.config/hyde/config.toml ` ??

config.toml for futureproof and also extensibility.

The name.toml would make sense if there was no folder

**Comment by kRHYME7** [comment]
Will merge this now. Please report issues immediately. Thanks! (requires relogin for the parser to work)

**Pull request merged**
