### PR TITLE
Hyprlock + Hypridle

### PR DESCRIPTION
**Pull request by abenezerw**
Re-work of Khings original PR #1173 
```
+ All 3 layouts done ✅
+ Dynamic wallpaper same as background ✅
+ Dynamic color accents same as theme ✅
+ Restructured a few modules and cleaned them ✅

+ Positioned them like this on purpose for layout 1 because I have the same style and colors for sddm config, 
for a pr after this.
+ sddm config also added ✅
+ need to work on user avatar for sddm though
 ```

# Layout 1 
layout1tt3
layout1ttt
layout1tttt
layout11212
layouttt

# Layout 3

# Layout 2

# [SDDM configs](https://github.com/abenezerw/Hy-sddm/tree/main)
sddm

### CODE REVIEW

**Comment by rubiin** [comment]
i think we can merge this. my 2 cents

**Comment by kRHYME7** [comment]
I'm gonna merge this but expect some changes, not with the layout but how we manage  the files. I'll be honest this PR is mature enough. Thank you @abenezerw !

Also thank you for understanding that I can't merge the one in hyprdots.

**Review by kRHYME7 — CHANGES_REQUESTED** [review]
@rubiin  Look, @abenezerw  wanted to remove the pokego package Hahaha.

Kidding! This looks like a mistake?

**Comment by rubiin** [comment]
I guess this PR was originally from hyprdots thats where the package was replaced IG :D

**Comment by kRHYME7** [comment]
@abenezerw  I think I will make a separate branch to merge this PR. we don't need the hyprlock.dcol now as hyprland has this too and we can just source it .

**Comment by abenezerw** [comment]
> @abenezerw I think I will make a separate branch to merge this PR. we don't need the hyprlock.dcol now as hyprland has this too and we can just source it .
> 
> https://github.com/HyDE-Project/HyDE/pull/9 Checkout this dev branch for hyprlock

Yeah I don’t really understand what goes where now. And pokego was an accident don’t know where I deleted it. I would wanna try this repo but I don’t know if it’s ready yet and installing might crash?

**Comment by kRHYME7** [comment]
better to try this on a separate User

**Comment by kRHYME7** [comment]
@abenezerw  https://github.com/HyDE-Project/HyDE/blob/efc7058ecbce96b831def559ac06e82eb2217fa3/Configs/.config/hypr/hyprlock.conf

Here are the instrructions on adding a layout. 

about the font whcih is very crucial for hyprlock aesthetics I will push a script in resolving fonts later.

**Comment by kRHYME7** [comment]
DONE! 

We needed to tweak some colors though. Also just named the layout with the font name for now 

https://github.com/user-attachments/assets/8d8ff6ba-f408-445e-b240-b81ce04bd62a

**Pull request closed without merging**
