### PR TITLE
fix: Fix activation of sunset on startup

### PR DESCRIPTION
**Pull request by Anshul-007**
# Pull Request

## Description

- added code for launching hyprsunset on startup if user kept it running while he shutdown.
- previously it read the json file on startup and if user mode is set then it doesn't take action to enable it. So now we can read it from runnig instance of hyprsunset and compare it with json if not comaparable. Thus we can enable hyprsunset

## Type of change

Please put an `x` in the boxes that apply:

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [x] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by kRHYME7** [comment]
@Anshul-007  BTW why did you capped it to 10k ?  max is 20k

**Comment by kRHYME7** [comment]
> Should i push it to 20k as well 

yes

**Comment by kRHYME7** [comment]
ready for merging?

**Comment by kRHYME7** [comment]
BTW I wanted to add something to this script later.

basically we need to use percent or 1-100 as values.

It's easy though, It's already implemented on the old hyprsunset.sh

this is more intuitive than learning how much 500 steps is.

**Comment by Anshul-007** [comment]
Will look into it.

**Pull request merged**
