### PR TITLE
Feat: Enhanced Fastfetch

### PR DESCRIPTION
**Pull request by abenezerw**
Better looks.
More Info.

### CODE REVIEW

**Comment by kRHYME7** [comment]
Cool!



What can we possibly put in here. I'm planning to change this one cause I don't understand it Lols

**Comment by s0m3th1ng-r4nd0m** [comment]
@kRHYME7 it just says Computer in Katakana and i don't know why it is there either. I know it is a computer.

**Comment by kRHYME7** [comment]
I'll probably make the fastfetch configs a custom one. and make a fastfetch.sh as wrapper for fastfetch icons to be generated. this way if someone who wants to customize it can freely do so and it depends  on them to use the fastfetch.sh command to randomize the image. 

this way we can make a wrapper to generate icons per theme  and themes can ship their own `{filename}.icon `  and if exist the wrapper will use it. making fastfetch as one with the themes. Cool with this one?

**Comment by s0m3th1ng-r4nd0m** [comment]
@kRHYME7 sounds great!

**Comment by abenezerw** [comment]
> I'll probably make the fastfetch configs a custom one. and make a fastfetch.sh as wrapper for fastfetch icons to be generated. this way if someone who wants to customize it can freely do so and it depends on them to use the fastfetch.sh command to randomize the image.
> 
> this way we can make a wrapper to generate icons per theme and themes can ship their own `{filename}.icon ` and if exist the wrapper will use it. making fastfetch as one with the themes. Cool with this one?

great idea. should i just close this or?

**Comment by kRHYME7** [comment]
@abenezerw   will merge this still. I kinda like it. and future changes will be decided by you guys from the DC channel. Help me shape a good default layout

**Review by kRHYME7 — APPROVED** [review]

**Pull request merged**
