### PR TITLE
Update hyde.conf

### LINKED ISSUE #63: [Bug]: Mouse
There is a bug that makes the mouse very big

### PR DESCRIPTION
**Pull request by JoeArchV**
cursor size fixed!

closes #63

### CODE REVIEW

**Review by kRHYME7 — APPROVED** [review]

**Comment by kRHYME7** [comment]
try to use 24 is it the same as 20?

**Comment by JoeArchV** [comment]
I will change it to 24

**Comment by JoeArchV** [comment]
ready

**Comment by kRHYME7** [comment]
Try to do it in your local.

Basically this is  not a fix. It only works with monitors with  scaling of 1. That's why the default is bigger as I'm using hidpi monitor. It is fone though assuming that most of the users have monitors with x1 scaling.

**Comment by kRHYME7** [comment]
> ready


wrong file do it in this one

https://github.com/HyDE-Project/HyDE/blob/d6243beb5ea22d3132e9798644f1373d4ee816d3/Configs/.local/share/hyde/hyprland.conf#L115

**Comment by JoeArchV** [comment]
The code view is read-only.

**Pull request closed without merging**
