### PR TITLE
feat: reusable keybind parser

### LINKED ISSUE #48: [Bug]: function key not working and hints undone
Hiya ^^ after getting everything running from hyde project with a clean install. I found that the win key and A no longer opens the apps and also the hints for key strokes look strange.

### PR DESCRIPTION
**Pull request by kRHYME7**
# Pull Request

-  Uses python instead of jq + perl  on parsing the keybinds. ( I can't maintain the old script anymor )
- Added some optional grouping. To organize the hints to be reusable eg. GUI. provide json , md,dmenu and rofi outputs 

closes #48   #42

# Screenshots
SS later

### CODE REVIEW

**Comment by kRHYME7** [comment]
@Anshul-007  Are the scripts good?  we can stall the keybindings.conf for now . That can wait.

**Comment by Anshul-007** [comment]
yes they worked great on my machine

**Comment by kRHYME7** [comment]
@Anshul-007 @rubiin    Will you review this one

**Comment by kRHYME7** [comment]
DM me immediately when it breaks! Thanks!

**Pull request merged**
